<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_Matrix4x4" Id="{f4a9e808-a4c0-4a90-8187-6ad211a90c89}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PUBLIC FB_Matrix4x4 EXTENDS ExternalStaticMatrix
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	data_array : ARRAY [0..15] OF LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{f12619f9-cf19-4eaa-9b1a-bbbfc7ecfb01}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
END_VAR
VAR
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[Init(ADR(data_array), 4, 4);
Clear();]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Matrix4x4">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Matrix4x4.FB_init">
      <LineId Id="7" Count="0" />
      <LineId Id="10" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>