# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Ui_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1226, 892)
        MainWindow.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        MainWindow.setAccessibleName("")
        MainWindow.setAccessibleDescription("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_ResetEStop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ResetEStop.setGeometry(QtCore.QRect(10, 310, 191, 41))
        self.pushButton_ResetEStop.setObjectName("pushButton_ResetEStop")
        self.pushButton_SafetyDriveAxisReset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_SafetyDriveAxisReset.setGeometry(QtCore.QRect(10, 370, 191, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.pushButton_SafetyDriveAxisReset.sizePolicy().hasHeightForWidth())
        self.pushButton_SafetyDriveAxisReset.setSizePolicy(sizePolicy)
        self.pushButton_SafetyDriveAxisReset.setAutoDefault(False)
        self.pushButton_SafetyDriveAxisReset.setObjectName("pushButton_SafetyDriveAxisReset")
        self.label_Joint1 = QtWidgets.QLabel(self.centralwidget)
        self.label_Joint1.setGeometry(QtCore.QRect(20, 640, 47, 14))
        self.label_Joint1.setObjectName("label_Joint1")
        self.label_Joint2 = QtWidgets.QLabel(self.centralwidget)
        self.label_Joint2.setGeometry(QtCore.QRect(20, 680, 47, 14))
        self.label_Joint2.setObjectName("label_Joint2")
        self.label_Joint3 = QtWidgets.QLabel(self.centralwidget)
        self.label_Joint3.setGeometry(QtCore.QRect(20, 710, 47, 14))
        self.label_Joint3.setObjectName("label_Joint3")
        self.label_SetJointPosition = QtWidgets.QLabel(self.centralwidget)
        self.label_SetJointPosition.setGeometry(QtCore.QRect(130, 580, 161, 16))
        self.label_SetJointPosition.setObjectName("label_SetJointPosition")
        self.pushButton_PositionModeExecute = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_PositionModeExecute.setGeometry(QtCore.QRect(100, 740, 141, 41))
        self.pushButton_PositionModeExecute.setObjectName("pushButton_PositionModeExecute")
        self.label_EStopStatus = QtWidgets.QLabel(self.centralwidget)
        self.label_EStopStatus.setGeometry(QtCore.QRect(920, 80, 91, 16))
        self.label_EStopStatus.setObjectName("label_EStopStatus")
        self.label_CurrentJointAngles = QtWidgets.QLabel(self.centralwidget)
        self.label_CurrentJointAngles.setGeometry(QtCore.QRect(420, 500, 121, 16))
        self.label_CurrentJointAngles.setObjectName("label_CurrentJointAngles")
        self.label_EStopPressed = QtWidgets.QLabel(self.centralwidget)
        self.label_EStopPressed.setGeometry(QtCore.QRect(1120, 60, 50, 50))
        self.label_EStopPressed.setObjectName("label_EStopPressed")
        self.pushButton_AckSafetyGroup = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_AckSafetyGroup.setGeometry(QtCore.QRect(10, 250, 191, 41))
        self.pushButton_AckSafetyGroup.setIconSize(QtCore.QSize(25, 16))
        self.pushButton_AckSafetyGroup.setObjectName("pushButton_AckSafetyGroup")
        self.graphicsLayoutWidget_JointAnglePlot = GraphicsLayoutWidget(self.centralwidget)
        self.graphicsLayoutWidget_JointAnglePlot.setGeometry(QtCore.QRect(660, 460, 561, 371))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsLayoutWidget_JointAnglePlot.setBackgroundBrush(brush)
        self.graphicsLayoutWidget_JointAnglePlot.setObjectName("graphicsLayoutWidget_JointAnglePlot")
        self.lcdNumber_CurrentJoint1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_CurrentJoint1.setGeometry(QtCore.QRect(430, 550, 101, 31))
        self.lcdNumber_CurrentJoint1.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumber_CurrentJoint1.setObjectName("lcdNumber_CurrentJoint1")
        self.lcdNumber_CurrentJoint2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_CurrentJoint2.setGeometry(QtCore.QRect(430, 590, 100, 31))
        self.lcdNumber_CurrentJoint2.setObjectName("lcdNumber_CurrentJoint2")
        self.lcdNumber_CurrentJoint3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_CurrentJoint3.setGeometry(QtCore.QRect(430, 630, 101, 31))
        self.lcdNumber_CurrentJoint3.setObjectName("lcdNumber_CurrentJoint3")
        self.doubleSpinBox_SetJoint1Position = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_SetJoint1Position.setGeometry(QtCore.QRect(131, 621, 101, 31))
        self.doubleSpinBox_SetJoint1Position.setMinimum(-180.0)
        self.doubleSpinBox_SetJoint1Position.setMaximum(180.0)
        self.doubleSpinBox_SetJoint1Position.setObjectName("doubleSpinBox_SetJoint1Position")
        self.doubleSpinBox_SetJoint2Position = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_SetJoint2Position.setGeometry(QtCore.QRect(130, 660, 101, 31))
        self.doubleSpinBox_SetJoint2Position.setMinimum(-180.0)
        self.doubleSpinBox_SetJoint2Position.setMaximum(180.0)
        self.doubleSpinBox_SetJoint2Position.setObjectName("doubleSpinBox_SetJoint2Position")
        self.doubleSpinBox_SetJoint3Position = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_SetJoint3Position.setGeometry(QtCore.QRect(130, 700, 101, 31))
        self.doubleSpinBox_SetJoint3Position.setMinimum(-180.0)
        self.doubleSpinBox_SetJoint3Position.setMaximum(180.0)
        self.doubleSpinBox_SetJoint3Position.setObjectName("doubleSpinBox_SetJoint3Position")
        self.checkBox_EnableManualControl = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_EnableManualControl.setGeometry(QtCore.QRect(20, 480, 221, 41))
        self.checkBox_EnableManualControl.setObjectName("checkBox_EnableManualControl")
        self.pushButton_ResetRobot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ResetRobot.setGeometry(QtCore.QRect(240, 30, 100, 100))
        self.pushButton_ResetRobot.setObjectName("pushButton_ResetRobot")
        self.pushButton_Stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Stop.setGeometry(QtCore.QRect(480, 30, 100, 100))
        self.pushButton_Stop.setAutoFillBackground(False)
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.doubleSpinBox_SetJoint3Velocity = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_SetJoint3Velocity.setGeometry(QtCore.QRect(270, 690, 101, 31))
        self.doubleSpinBox_SetJoint3Velocity.setMinimum(-180.0)
        self.doubleSpinBox_SetJoint3Velocity.setMaximum(180.0)
        self.doubleSpinBox_SetJoint3Velocity.setObjectName("doubleSpinBox_SetJoint3Velocity")
        self.doubleSpinBox_SetJoint1Velocity = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_SetJoint1Velocity.setGeometry(QtCore.QRect(271, 611, 101, 31))
        self.doubleSpinBox_SetJoint1Velocity.setMinimum(-180.0)
        self.doubleSpinBox_SetJoint1Velocity.setMaximum(180.0)
        self.doubleSpinBox_SetJoint1Velocity.setObjectName("doubleSpinBox_SetJoint1Velocity")
        self.label_SetJointVelocity = QtWidgets.QLabel(self.centralwidget)
        self.label_SetJointVelocity.setGeometry(QtCore.QRect(270, 580, 161, 16))
        self.label_SetJointVelocity.setObjectName("label_SetJointVelocity")
        self.doubleSpinBox_SetJoint2Velocity = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_SetJoint2Velocity.setGeometry(QtCore.QRect(270, 650, 101, 31))
        self.doubleSpinBox_SetJoint2Velocity.setMinimum(-180.0)
        self.doubleSpinBox_SetJoint2Velocity.setMaximum(180.0)
        self.doubleSpinBox_SetJoint2Velocity.setObjectName("doubleSpinBox_SetJoint2Velocity")
        self.checkBox_PositionMode = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_PositionMode.setGeometry(QtCore.QRect(110, 510, 221, 41))
        self.checkBox_PositionMode.setObjectName("checkBox_PositionMode")
        self.checkBox_VelocityMode = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_VelocityMode.setGeometry(QtCore.QRect(260, 510, 221, 41))
        self.checkBox_VelocityMode.setObjectName("checkBox_VelocityMode")
        self.label_RobotStatus = QtWidgets.QLabel(self.centralwidget)
        self.label_RobotStatus.setGeometry(QtCore.QRect(1120, 10, 50, 50))
        self.label_RobotStatus.setObjectName("label_RobotStatus")
        self.pushButton_PowerOnRobot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_PowerOnRobot.setGeometry(QtCore.QRect(20, 30, 100, 100))
        self.pushButton_PowerOnRobot.setAutoFillBackground(False)
        self.pushButton_PowerOnRobot.setObjectName("pushButton_PowerOnRobot")
        self.label_EStopStatus_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_EStopStatus_2.setGeometry(QtCore.QRect(920, 30, 151, 20))
        self.label_EStopStatus_2.setObjectName("label_EStopStatus_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1226, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_SafetyDriveAxisReset, self.pushButton_ResetEStop)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.setToolTip(_translate("MainWindow", "<html><head/><body><p>Joint 1</p></body></html>"))
        self.pushButton_ResetEStop.setText(_translate("MainWindow", "Reset E-Stop"))
        self.pushButton_SafetyDriveAxisReset.setText(_translate("MainWindow", "Safety Drive Axis Reset"))
        self.label_Joint1.setText(_translate("MainWindow", "Join-1"))
        self.label_Joint2.setText(_translate("MainWindow", "Joint-2"))
        self.label_Joint3.setText(_translate("MainWindow", "Joint-3"))
        self.label_SetJointPosition.setText(_translate("MainWindow", "Set Joint Position"))
        self.pushButton_PositionModeExecute.setText(_translate("MainWindow", "Position Mode Execute"))
        self.label_EStopStatus.setText(_translate("MainWindow", "E-Stop Status"))
        self.label_CurrentJointAngles.setText(_translate("MainWindow", "Current Joint Angles"))
        self.label_EStopPressed.setText(_translate("MainWindow", "E-Stop Pressed"))
        self.pushButton_AckSafetyGroup.setText(_translate("MainWindow", "Safety Group Err Ack"))
        self.checkBox_EnableManualControl.setText(_translate("MainWindow", "Enable Manual Control"))
        self.pushButton_ResetRobot.setText(_translate("MainWindow", "Reset Robot"))
        self.pushButton_Stop.setText(_translate("MainWindow", "Stop"))
        self.label_SetJointVelocity.setText(_translate("MainWindow", "Set Joint Velocity"))
        self.checkBox_PositionMode.setText(_translate("MainWindow", "Position  Mode"))
        self.checkBox_VelocityMode.setText(_translate("MainWindow", "Velocity Mode"))
        self.label_RobotStatus.setText(_translate("MainWindow", "Robot Status"))
        self.pushButton_PowerOnRobot.setText(_translate("MainWindow", "Power On Robot"))
        self.label_EStopStatus_2.setText(_translate("MainWindow", "Robot Power Status"))
from pyqtgraph import GraphicsLayoutWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
