<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="RescaleRange" Id="{01836272-1a98-4336-98f7-9ee27f8d7a56}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION RescaleRange : LREAL
VAR_INPUT
	in: LREAL;
	in_min: LREAL;
	in_max: LREAL;
	out_min: LREAL;
	out_max: LREAL;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[in := LIMIT(in_min, in, in_max);
RescaleRange := LIMIT(out_min, (out_min + (in - in_min)*(out_max-out_min)/(in_max-in_min)), out_max);]]></ST>
    </Implementation>
    <LineIds Name="RescaleRange">
      <LineId Id="3" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>